### PR TITLE
Added Train-Case feature

### LINKED ISSUE #10: feat: add train case
The request "header" keys are typically set as kebab-case but with the first letters as in capital.

See the Postman screenshot:

2021-12-28 at 21 37 18@2x

The normal "kebab-case" transforms the full string to lowercase.
To facilitate the automatic casing of header keys, it want to get your input if you would be open for a PR to introduce an additional casing: `Capital-Kebab-Case`?

```js
/**
 * converts strings to Capital-Kebab-Case
 *
 * @export
 * @param {string} string
 * @returns {string} in Kebab-Case
 */
function capitalKebabCase(string) {
    return getParts(string, noSpecialChars)
        .map(part => capitaliseWord(part))
        .join('-')
}
```

Example:
`capitalKebabCase('ponytaVaporeonPOLIWRATH_ButterfreeA')` => `Ponyta-Vaporeon-Poliwrath-Butterfree-A`

Any feedback on the idea is welcome.

### PR DESCRIPTION
**Pull request by thim81**
fixes #10

### CODE REVIEW

**Comment by thim81** [comment]
@mesqueeb I was not able to "build" it, so I could not test the code change.

I kept running into 98 errors like:
/Users/Haselaars/Sites/case-anything/src/index.js
   2:23   error  Cannot determine side-effects of calling LogicalExpression  tree-shaking/no-side-effects-in-initialization
   9:1    error  Cannot determine side-effects of mutating global variable   tree-shaking/no-side-effects-in-initialization
   9:1    error  'exports' is not defined

**Comment by mesqueeb** [comment]
@thim81 thanks for the PR!

you should be able to run the tests without having to execute `npm run build`, so just try `npm run test`. it uses the source code without relying on the built folder ;)

did your tests pass?

**Comment by mesqueeb** [comment]
trouwens, ik weet niet 100% zeker of jij van Vlaanderen bent, maar ik ben oorspronkelijk van Antwerpen. : P
Ik ga nu net naar bed, ik zal't morgen releasen!

**Comment by thim81** [comment]
ik ben ook van Vlaanderen, Limburg :-) Kleine wereld, om samen te werken op Github

**Comment by thim81** [comment]
en dankzij je tip heb ik de test kunnen runnen.

2021-12-29 at 16 44 34@2x

**Pull request merged**
