### PR TITLE
Add Russian language support

### PR DESCRIPTION
**Pull request by lordoys**
Add Russian language support

### CODE REVIEW

**Comment by lordoys** [comment]
@mesqueeb 
Take a look, please. Just a few characters will allow you to work with Russian text. It won't affect performance, but will help many developers. Thank you!

**Comment by mesqueeb** [comment]
@lordoys thanks a lot ! 
Can you also update the readme. I mention something about the regex that will need to be updated.

**Comment by lordoys** [comment]
Done  ✅

**Comment by lordoys** [comment]
@mesqueeb

**Comment by lordoys** [comment]
@mesqueeb Hi, just reminding you of myself.

**Pull request closed without merging**
